### PR TITLE
Make database tests work again

### LINKED ISSUE #164: Get Database tests running
## Description
Database tests as they are right now don't work. You can execute them manually, but Xcode or Bitrise won't find them since they are swift generic classes and those are not compatible with `XCTestCase`

So... that means they have to be refactored some how so they work. Your mission, should you choose to accept it, is exactly that.

## Definition of done
- [ ] Exactly the same tests that can be now manually run are automatically run 
- [ ] Those tests run in Xcode (when hitting command + u) and in Bitrise

### PR DESCRIPTION
**Pull request by juanlaube**
## Info
This makes the database tests work (again).

### Summary
The database tests didn't work because XCTest cannot discover instantiate Swift generic classes at runtime, it uses the ObjC runtime for that.

### Technical considerations
This solution moves the tests cases to new classes and adds a new class that can be instantiated at runtime for each one of the original class, then programmatically instantiates and executes all the tests cases.

### Why is it done like this and not some other way?
It's the simplest way to solve the problem.

### Relationships
Closes #164 

### Pull Request checklist
- [x] The code does not hinder the app's performance
- [x] The code does not introduce regressions
- [x] The code in this PR is tested thoroughly enough that changing the behavior to an incorrect one breaks tests
- [ ] The code used custom templates

### Pointers
Not much I can add here, it's just a workaround using some XCTest magic to make things work.

### Review template

- [ ] The code is thoroughly tested in well written and resilient manner
- [ ] The code is performant and leads to an optimal user experience
- [ ] The code is testable and does not cut corners for the sake of delivering
- [ ] The code considers older platforms well and will work in older devices just like it will in new ones

- [ ] The code considers light and dark theme
- [ ] The code considers RTL and does not mention left/right
- [ ] The code considers i18n
  - [ ] There are no hardcoded strings in the UI
  - [ ] All strings are included in every language we support OR there's an issue requesting new translations
- [ ] There are no hard-coded numbers referring to dimensions or font sizes
- [ ] The code considers UI elements that are similar and extracts their similarities into styles to avoid duplication

## Merge permissions

🦑

### CODE REVIEW

**Comment by juanlaube** [comment]
That's a good idea, I removed the additional classes and made things work from the `DatabaseTests` class.

**Comment by juanlaube** [comment]
For some reason this is failing in Bitrise and I couldn't figure out why yet.

**Comment by Odrakir** [comment]
It fails locally to. [Here](https://github.com/toggl/ios/blob/aa4615352096e58bbe235b35c9aef46eaf6142d1/Modules/Database/DatabaseTests/EntityDatabaseTests.swift#L153) with a "Could not merge changes." error.

To fix it add this in line 43
```
container.viewContext.mergePolicy = NSMergeByPropertyObjectTrumpMergePolicy
```

**Comment by juanlaube** [comment]
@Odrakir that doesn't seem to solve the issue, and for some reason the tests do not fail for me locally 🤔

**Comment by Odrakir** [comment]
If you delete the app from the simulator I think you'll see tests fails... I think there's something wrong with the in memory DB... I'm researching it.

**Comment by heytherewill** [comment]
Is anything blocking this PR? How can we unblock it?

ping @juanlaube

**Comment by juanlaube** [comment]
I don't know what else to try so I'm waiting for enlightenment or for @Odrakir to find a solution, whatever comes first 😄

**Comment by Odrakir** [comment]
I didn't know you were expecting me to look more into this... I'm currently out of ideas, but since this is not really urgent we can let it rest a bit more.

As a last resort, as I said on Slack, we could make the Database a dynamic framework (and move the model back from assets)

**Comment by Odrakir** [comment]
Juan, I think the best thing to do for now is making this a dynamic framework and moving the model file back to it from Assets. Do you want me to do it or do you want to do it?

**Comment by Odrakir** [comment]
Yay! The problem was flushing the data from the in memory database in tests. I opted for deleting the persistent store completely.

**Comment by Odrakir** [comment]
Done. In the end this had to do with the tests, switching the the main thread before blocking the observable fixed it.

**Pull request merged**
