### PR TITLE
Settings: Add settings button to calendar view 

### LINKED ISSUE #660: Settings: Add settings button to calendar view
## Description
 Add settings button to calendar view

## Dependencies
#481 

## Definition of done
- [ ] Add the button as show in the designs to the calendar view
- [ ] Open the settings modally when button tapped

### PR DESCRIPTION
**Pull request by dshr**
## Info
This PR adds the settings button to the calendar view, along with adding some required changes to the way we have organised our states.

### Technical considerations
This PR moves the settings state out of the timer state and makes it a direct child of the app state. To navigate to it we keep a flag in the AppState, which we pass to it's children states like the timer and calendar. We can replace this flag with a route property down the line.

### Relationships
Closes #660

### Pull Request checklist
- [x] The code does not hinder the app's performance
- [x] The code does not introduce regressions
- [x] The code in this PR is tested thoroughly enough that changing the behavior to an incorrect one breaks tests

### Pointers
Commit by commit

### Review template
- [ ] The code is thoroughly tested in well written and resilient manner
- [ ] The code is performant and leads to an optimal user experience
- [ ] The code is testable and does not cut corners for the sake of delivering
- [ ] The code considers older platforms well and will work in older devices just like it will in new ones
- [ ] The code considers light and dark theme
- [ ] The code considers RTL and does not mention left/right
- [ ] The code considers i18n
  - [ ] There are no hardcoded strings in the UI
  - [ ] All strings are included in every language we support OR there's an issue requesting new translations
- [ ] There are no hard-coded numbers referring to dimensions or font sizes
- [ ] The code considers UI elements that are similar and extracts their similarities into styles to avoid duplication

## Merge permissions
Go for it!

### CODE REVIEW

**Comment by sofokli1** [comment]
looks like there a couple more issues about this button #672 #481 handled in https://github.com/toggl/ios/pull/701

**Comment by simonrozsival** [comment]
Is this needed after #701 was merged?

**Comment by dshr** [comment]
Yes, this clears up the state situation, making it work properly

**Review by simonrozsival — APPROVED** [review]
I managed to compile the app today :D It works just fine and I'm glad you managed to get rid of so much code duplicity!

**Review by sofokli1 — APPROVED** [review]
LGTM

**Pull request merged**
