### PR TITLE
Big package refactor

### LINKED ISSUE #720: Move to SPM & refactor dependencies
## Description
We want to use SPM and leave Cocoapods only for the frameworks that don't have a SPM alternative.

At the same time this is a good opportunity to refactor the dependencies. Relevant discussion: https://github.com/toggl/mobile-discussions/issues/79

## Definition of done
- [ ] The project uses SPM
- [ ] Dependencies are refactored following what's discussed
- [ ] The documentation is updated to reflect the changes done in this PR

### PR DESCRIPTION
**Pull request by Odrakir**
## Info
As I mentioned in Slack, I messed up the commit history, so you can ignore that. But basically this moves most files around, so in any case review of every single change is not an option.

This is the final package configuration.
image

## Summary
This is what I did.
- Extracted every project into Swift Packages. I, more or less, kept the same module organization except when mentioned
- Separated Utils in Utils and UIKitUtils
- Remove references from Utils & Models to Assets. If we have an extension or custom UI that needs project Assets that will go in `SharedUI` (changed `prependingImage` to take an image and not depend on Assets, for example)
- Remove DB and TextFiles from Assets and put them in Database and API respectively
- Add static methods to Assets to instantiate Storyboards (refactored Storyboarded to work with that) and Nibs
- Moved localizable strings out of the API and the models and into SharedUI
- Moved CalendarEvent, EditableTimeEntry and EditableProject to Models
- Renamed CommonFeatures to FeaturesShared
- Extracted test realted code from Architecture into ArchitectureTestSupport
- Disabled SSO stuff for now, since that should go into its own service, the way we do with analytics
- Dragged TogglTrack to workspace, add it to Frameworks, Libraries & Embedded content

### Stuff left
These are other things that I would like to do, I'll create issues for them:
- Review .iOS(.vXX) requirements (I'm defaulting to iOS, but we should include other platforms)
- Split Networking into live and fake targets
- Split OtherServices to put UserDefaultsMock in another target
- Put equalContents somewhere else rather than Utils, it's only accessed in tests
- Maybe split utils to extract the ones that don't rely on RxSwift
- Re-enable SSO
- Extract TestSupport from FeaturesShared
- Fix access to UIKit from SettingsReducer
- Clean configurations
- Run tests for all local dependencies

### Relationships
Closes #720 

### Pull Request checklist
- [ ] The code does not hinder the app's performance
- [ ] The code does not introduce regressions
- [ ] The code in this PR is tested thoroughly enough that changing the behavior to an incorrect one breaks tests

### Pointers
Let's have a talk, and then review all those points I mentioned up there, see if they make sense and test the app thoroughly.

### Review template

- [ ] The code is thoroughly tested in well written and resilient manner
- [ ] The code is performant and leads to an optimal user experience
- [ ] The code is testable and does not cut corners for the sake of delivering
- [ ] The code considers older platforms well and will work in older devices just like it will in new ones

- [ ] The code considers light and dark theme
- [ ] The code considers RTL and does not mention left/right
- [ ] The code considers i18n
  - [ ] There are no hardcoded strings in the UI
  - [ ] All strings are included in every language we support OR there's an issue requesting new translations
- [ ] There are no hard-coded numbers referring to dimensions or font sizes
- [ ] The code considers UI elements that are similar and extracts their similarities into styles to avoid duplication

### CODE REVIEW

**Comment by Odrakir** [comment]
Something else we need to do is change the bitrise stack, this needs Xcode 12 beta.

**Comment by sofokli1** [comment]
I can't run tests. xcode crashes every time with same error. Main points I saw are the mention of `Networking/Sources/Networking/TextFiles` and the method `+_retainedContainerAtFilePath:fileDataType:workspace:options:error:`

stack trace below
```
Application Specific Information:
ProductBuildVersion: 12A8189n
ASSERTION FAILURE in /Library/Caches/com.apple.xbs/Sources/IDEFrameworks/IDEFrameworks-17210.1/IDEFoundation/ProjectModel/Containers/IDEContainer.m:580
Details:  Error: Mismatch between existing container extension: <DVTExtension 0x7fbb250551c0: Swift User Managed Package Folder (Xcode.IDEFoundation.Container.SwiftPackageUserManagedFolder) from com.apple.dt.IDE.IDESwiftPackageSupport> and requested container extension: <DVTExtension 0x7fbb24f575b0: Folder (Xcode.IDEFoundation.Container.Folder) from com.apple.dt.IDEFoundation> for file path: <DVTFilePath:0x7fbb2e1ec910:'/Users/sofokli1/Development/ios/Dependencies/Networking/Sources/Networking/TextFiles'>
Object:   <IDEContainer>
Method:   +_retainedContainerAtFilePath:fileDataType:workspace:options:error:
Thread:   <NSThread: 0x7fbb1fc1bfe0>{number = 1, name = main}
Open FDs: 56/9472
Hints:   
 
Backtrace:
  0   -[IDEAssertionHandler handleFailureInMethod:object:fileName:lineNumber:assertionSignature:messageFormat:arguments:] (in IDEKit)
  1   _DVTAssertionHandler (in DVTFoundation)
  2   _DVTAssertionFailureHandler (in DVTFoundation)
  3   __82+[IDEContainer _retainedContainerAtFilePath:fileDataType:workspace:options:error:]_block_invoke_2 (in IDEFoundation)
  4   _dispatch_client_callout (in libdispatch.dylib)
  5   _dispatch_lane_barrier_sync_invoke_and_complete (in libdispatch.dylib)
  6   DVTDispatchBarrierSync (in DVTFoundation)
  7   -[DVTDispatchLock performLockedBlock:] (in DVTFoundation)
  8   __82+[IDEContainer _retainedContainerAtFilePath:fileDataType:workspace:options:error:]_block_invoke (in IDEFoundation)
  9   -[DVTModelObjectGraph performBlockCoalescingModelChanges:] (in DVTFoundation)
 10   +[IDEContainer _retainedContainerAtFilePath:fileDataType:workspace:options:error:] (in IDEFoundation)
 11   +[IDEContainer retainedContainerAtFilePath:fileDataType:workspace:error:] (in IDEFoundation)
 12   -[IDEFileReference _recalculateReferencedContainer] (in IDEFoundation)
 13   -[IDEFileReference referencedContainer] (in IDEFoundation)
 14   __38-[IDEWorkspace _setupContainerQueries]_block_invoke (in IDEFoundation)
 15   -[IDEContainerQuery _processContainerGraphObject:insertedMatches:deletedMatches:] (in IDEFoundation)
 16   -[IDEContainerQuery _traverseContainerGraphObject:forDeletion:checkedContainers:insertedMatches:deletedMatches:] (in IDEFoundation)
 17   -[IDEContainerQuery _traverseContainerGraphObjects:forDeletion:insertedMatches:deletedMatches:] (in IDEFoundation)
 18   -[IDEContainerQuery _objectsDidChange:] (in IDEFoundation)
 19   __CFNOTIFICATIONCENTER_IS_CALLING_OUT_TO_AN_OBSERVER__ (in CoreFoundation)
 20   ___CFXRegistrationPost1_block_invoke (in CoreFoundation)
 21   _CFXRegistrationPost1 (in CoreFoundation)
 22   ___CFXNotificationPost_block_invoke (in CoreFoundation)
 23   -[_CFXNotificationRegistrar find:object:observer:enumerator:] (in CoreFoundation)
 24   _CFXNotificationPost (in CoreFoundation)
 25   -[NSNotificationCenter postNotificationName:object:userInfo:] (in Foundation)
 26   -[NSNotificationCenter(DVTNSNotificationCenterAdditions_MRR) _dvt_postNotificationName:object:userInfo:] (in DVTFoundation)
 27   -[DVTModelObjectGraph _coalescingTick] (in DVTFoundation)
 28   __58-[DVTModelObjectGraph performBlockCoalescingModelChanges:]_block_invoke (in DVTFoundation)
 29   -[DVTModelGraphTransactionScope performTransaction:] (in DVTFoundation)
 30   -[DVTModelObjectGraph performBlockCoalescingModelChanges:] (in DVTFoundation)
 31   -[IDEFileReference _invalidateStartingWith:changeBlock:] (in IDEFoundation)
 32   -[IDEFileReference _invalidateResolvedFilePath] (in IDEFoundation)
 33   -[IDEFileReference _setContainer:] (in IDEFoundation)
 34   -[IDEContainerItem _setSuperitem:] (in IDEFoundation)
 35   IDESwiftPackageBlueprint.sourceCodeBuildFileReferences() (in IDESwiftPackageCore)
 36   @objc IDESwiftPackageBlueprint.sourceCodeBuildFileReferences() (in IDESwiftPackageCore)
 37   +[IDECoverageBuildableInfo infoForBuildable:withBuildParameterVariants:] (in IDEFoundation)
 38   IDETestPlan.coverageBuildableInfos(for:buildableResolver:buildParameterVariants:) (in IDEFoundation)
 39   @objc IDETestPlan.coverageBuildableInfos(for:buildableResolver:buildParameterVariants:) (in IDEFoundation)
 40   -[IDEScheme _executionOperationForSchemeOperationParameters:build:onlyBuild:buildParameters:title:buildLog:dontActuallyRunCommands:restorePersistedBuildResults:deviceAvailableChecker:error:actionCallbackBlock:] (in IDEFoundation)
 41   -[IDEScheme schemeOperationForSchemeOperationParameters:buildLog:overridingProperties:overridingBuildConfiguration:dontActuallyRunCommands:restorePersistedBuildResults:deviceAvailableChecker:error:completionBlock:] (in IDEFoundation)
 42   -[IDEScheme startedOperationForSchemeOperationParameters:deviceAvailableChecker:error:completionBlock:] (in IDEFoundation)
 43   __151-[IDEWorkspaceTabController _actuallyPerformTaskOnScheme:forSchemeOperationParameters:useLegacyCompletionBehavior:enqueuingErrorBlock:completionBlock:]_block_invoke.1637 (in IDEKit)
 44   __54-[IDEWorkspaceDocument performBlockAfterPreBuildSave:]_block_invoke (in IDEKit)
 45   -[IDEDocumentController _saveEditorDocuments:forOperation:completionBlock:] (in IDEKit)
 46   -[IDEDocumentController saveAllEditorDocumentsAsynchronouslyWithCompletionBlock:] (in IDEKit)
 47   -[IDEWorkspaceDocument performBlockAfterPreBuildSave:] (in IDEKit)
 48   __151-[IDEWorkspaceTabController _actuallyPerformTaskOnScheme:forSchemeOperationParameters:useLegacyCompletionBehavior:enqueuingErrorBlock:completionBlock:]_block_invoke (in IDEKit)
 49   -[IDEWorkspaceTabController showStandardArchitecturesAlertForScheme:schemeCommand:runDestination:completionBlock:] (in IDEKit)
 50   -[IDEWorkspaceTabController _actuallyPerformTaskOnScheme:forSchemeOperationParameters:useLegacyCompletionBehavior:enqueuingErrorBlock:completionBlock:] (in IDEKit)
 51   __143-[IDEWorkspaceTabController _performTaskOnScheme:forSchemeOperationParameters:useLegacyCompletionBehavior:invokedViaScripting:completionBlock:]_block_invoke (in IDEKit)
 52   __146-[IDEWorkspaceTabController _performBlock:unlessBuildIsActiveWithScheme:forSchemeOperationParameters:useLegacyCompletionBehavior:completionBlock:]_block_invoke (in IDEKit)
 53   -[IDEWorkspaceTabController _performBlock:unlessBuildIsActiveWithScheme:forSchemeOperationParameters:useLegacyCompletionBehavior:completionBlock:] (in IDEKit)
 54   -[IDEWorkspaceTabController _performTaskOnScheme:forSchemeOperationParameters:useLegacyCompletionBehavior:invokedViaScripting:completionBlock:] (in IDEKit)
 55   __125-[IDEWorkspaceTabController _performDebuggableTaskOnScheme:forSchemeOperationParameters:invokedViaScripting:completionBlock:]_block_invoke_2 (in IDEKit)
 56   __125-[IDEWorkspaceTabController _performDebuggableTaskOnScheme:forSchemeOperationParameters:invokedViaScripting:completionBlock:]_block_invoke.2002 (in IDEKit)
 57   _dispatch_call_block_and_release (in libdispatch.dylib)
 58   _dispatch_client_callout (in libdispatch.dylib)
 59   _dispatch_main_queue_callback_4CF (in libdispatch.dylib)
 60   __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ (in CoreFoundation)
 61   __CFRunLoopRun (in CoreFoundation)
 62   CFRunLoopRunSpecific (in CoreFoundation)
 63   RunCurrentEventLoopInMode (in HIToolbox)
 64   ReceiveNextEventCommon (in HIToolbox)
 65   _BlockUntilNextEventMatchingListInModeWithFilter (in HIToolbox)
 66   _DPSNextEvent (in AppKit)
 67   -[NSApplication(NSEvent) _nextEventMatchingEventMask:untilDate:inMode:dequeue:] (in AppKit)
 68   -[DVTApplication nextEventMatchingMask:untilDate:inMode:dequeue:] (in DVTKit)
 69   -[NSApplication run] (in AppKit)
 70   NSApplicationMain (in AppKit)
 71   start (in libdyld.dylib)
 
abort() called

Application Specific Signatures:
(existingContainer->_extension == containerExtension)
```

**Comment by sofokli1** [comment]
I am getting the same xcode crash when running tests as posted earlier. seems related to `Networking/Sources/Networking/TextFiles`

**Comment by sofokli1** [comment]
making the following change seems to help 
`resources: [.copy("TextFiles")]`
to 
```
resources: [
                .copy("TextFiles/clients.txt"),
                .copy("TextFiles/me.txt"),
                .copy("TextFiles/projects.txt"),
                .copy("TextFiles/tags.txt"),
                .copy("TextFiles/tasks.txt"),
                .copy("TextFiles/timeentries.txt"),
                .copy("TextFiles/workspaces.txt")]
```

**Review by sofokli1 — APPROVED** [review]
other than the crashing of the tests, this seems good to go

**Pull request merged**
